version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}

  app:
    build: .
    image: app-image
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db

volumes:
  db:




# DOCKER                     HOST

# X:3306  >>   127.0.0.1:3306 

# Y:3306  >>   127.0.0.1:3306